DROP DATABASE IF EXISTS metadb;
CREATE DATABASE IF NOT EXISTS metadb DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `metadb`.`fields`;

use metadb;

CREATE TABLE `fields` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `struct_name` varchar(200) NOT NULL COMMENT '实体名',
  `name` varchar(50) NOT NULL COMMENT '字段名，如"orderNo"',
  `element` varchar(50) DEFAULT NULL COMMENT '替换元素，如 "paper-input" ',
  `label` varchar(50) NOT NULL COMMENT '字段名，如"订单号"',
  `required` smallint(1) NOT NULL DEFAULT '0' COMMENT '是否必填 1: 是 0：否',
  `multi` smallint(1) NOT NULL DEFAULT '0' COMMENT '是否多选  1: 是 0：否',
  `format` varchar(50) DEFAULT NULL COMMENT '显示格式，用于日期显示，如“yyyy-MM-dd”',
  `editable` smallint(1) NOT NULL DEFAULT '0' COMMENT '是否可编辑  1: 是 0：否',
  `validate` smallint(1) NOT NULL DEFAULT '0' COMMENT '是否需要校验， 1: 是 0：否',
  `length` int(11) DEFAULT NULL COMMENT '字符允许长度',
  `max_length` int(11) DEFAULT NULL COMMENT '允许最大长度',
  `min_length` int(11) DEFAULT NULL COMMENT '允许最小长度',
  `regexp` varchar(200) DEFAULT NULL COMMENT '正则匹配',
  `prompt` varchar(50) DEFAULT NULL COMMENT '校验失败时的提示语，如“请输入备注”',
  `min` int(11) DEFAULT NULL COMMENT '数字最小值',
  `max` int(11) DEFAULT NULL COMMENT '数字最大值',
  `candidates` varchar(1000) DEFAULT NULL COMMENT '下拉选项中的值，json串，如 [{value:1,label:"男"},{value:2,label:"女"}]',
  `candidate_label` varchar(50) DEFAULT NULL COMMENT '组件显示字段名，针对下拉组件、radio-group组件等，“label”',
  `candidate_value` varchar(50) DEFAULT NULL COMMENT '组件值字段名，针对下拉组件、radio-group组件等，“value”',
  `placeholder` varchar(50) DEFAULT NULL COMMENT 'placeholder',
  `src_key` varchar(50) DEFAULT NULL COMMENT '源字段名',
  `visible` smallint(1) NOT NULL DEFAULT '1' COMMENT '界面是否可见 1: 是 0：否',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int(11) DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int(11) DEFAULT NULL,
  `disabled` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `field_unique` (`struct_name`,`name`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='字段元数据';


INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TUpdateTaskRequest', 'priority', 'o2-select', '优先级', 1, 0, null, 1, 0, null, null, null, null, null, null, null, '[{"label":"高","value":1},{"label":"中","value":2},{"label":"低","value":3}]', 'label', 'value', null, null, 1, '2017-11-09 18:29:56', null, '2017-11-23 22:00:12', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TUpdateTaskRequest', 'communicationStyle', 'o2-select', '沟通方式', 0, 0, null, 1, 0, null, null, null, null, null, null, null, '[{"label":"微信","value":1},{"label":"QQ","value":2},{"label":"短信","value":3},{"label":"电话","value":4},{"label":"实地拜访","value":5},{"label":"其它","value":6}]', 'label', 'value', null, null, 1, '2017-11-09 18:29:56', null, '2017-11-23 22:00:12', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TUpdateTaskRequest', 'status', 'o2-select', '状态', 1, 0, null, 1, 0, null, null, null, null, null, null, null, '[{"label":"待处理","value":1},{"label":"处理中","value":2},{"label":"已处理","value":3},{"label":"无需处理","value":4}]', 'label', 'value', null, null, 1, '2017-11-09 18:29:56', null, '2017-11-17 01:53:37', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TUpdateTaskRequest', 'type', 'o2-select', '工单类型', 1, 0, null, 1, 0, null, null, null, null, null, null, null, '[{"label":"待办事项","value":1},{"label":"投诉","value":2},{"label":"回访记录","value":3}]', 'label', 'value', null, null, 1, '2017-11-09 18:29:56', null, '2017-12-05 12:56:21', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTask', 'communicationStyle', null, '沟通方式', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 0, '2017-11-09 17:23:20', null, '2017-11-09 17:26:53', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTask', 'handlerName', null, '经办人', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-09 17:23:20', null, '2017-11-22 10:10:22', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTask', 'problemDesc', null, 'problemDesc', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 0, '2017-11-09 17:23:20', null, '2017-11-09 17:25:50', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTask', 'resultDesc', null, 'resultDesc', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 0, '2017-11-09 17:23:20', null, '2017-11-09 17:25:50', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTask', 'createdAt', null, 'createdAt', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 0, '2017-11-09 17:23:21', null, '2017-11-09 17:25:50', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTask', 'createdBy', null, 'createdBy', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 0, '2017-11-09 17:23:21', null, '2017-11-09 17:25:50', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTask', 'updatedAt', null, '更新时间', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-09 17:23:21', null, '2017-11-09 17:27:08', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTask', 'updater', null, 'updatedBy', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 0, '2017-11-09 17:23:21', null, '2017-12-01 17:12:45', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTask', 'questions', null, 'questions', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 0, '2017-11-09 17:23:21', null, '2017-11-09 17:25:50', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTask', 'improvements', null, 'improvements', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 0, '2017-11-09 17:23:21', null, '2017-11-09 17:27:53', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTask', 'taskLogs', null, 'taskLogs', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 0, '2017-11-09 17:23:21', null, '2017-11-09 17:25:50', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTask', 'taskAttachments', null, 'taskAttachments', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 0, '2017-11-09 17:23:21', null, '2017-11-09 17:27:53', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTask', 'taskRemarks', null, 'taskRemarks', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 0, '2017-11-09 17:23:21', null, '2017-11-09 17:25:50', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTask', 'companyName', null, '公司名', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-09 17:26:30', null, '2017-11-09 17:26:30', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTask', 'taskNo', null, '工单编号', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-09 17:49:44', null, '2017-12-05 12:58:47', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTaskRequest', 'taskNo', 'm2-task-picker', '工单编号', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-09 17:51:03', null, '2017-12-05 12:58:21', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTaskRequest', 'companyId', 'm2-company-picker', '公司', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-09 17:51:03', null, '2017-11-21 02:40:11', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTaskRequest', 'type', 'm2-select-list', '工单类型', 0, 0, null, 1, 0, null, null, null, null, null, null, null, '[{"label":"待办事项","value":1},{"label":"投诉","value":2},{"label":"回访记录","value":3}]', 'label', 'value', null, null, 1, '2017-11-09 17:51:03', null, '2017-12-07 15:04:30', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTaskRequest', 'businessTypeId', 'm2-task-business-type-picker', '业务类型', 0, 0, null, 1, 0, null, null, null, null, null, null, null, '', '', '', null, null, 1, '2017-11-09 17:51:03', null, '2017-11-28 18:11:05', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTaskRequest', 'status', 'm2-select-list', '状态', 0, 0, null, 1, 0, null, null, null, null, null, null, null, '[{"label":"待处理","value":1},{"label":"处理中","value":2},{"label":"已处理","value":3},{"label":"无需处理","value":4}]', 'label', 'value', null, null, 1, '2017-11-09 17:51:03', null, '2017-12-07 15:04:30', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTaskRequest', 'handlerId', 'm2-staff-picker', '经办人', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-09 17:51:03', null, '2017-11-21 02:40:11', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTaskRequest', 'planAtStart', 'm2-date', '计划日期', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-09 17:51:03', null, '2017-11-21 02:40:11', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTaskRequest', 'planAtEnd', 'm2-date', '至', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-09 17:51:03', null, '2017-11-21 02:40:11', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTaskRequest', 'updateAtStart', 'm2-date', '更新日期', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-09 17:51:03', null, '2017-11-21 02:40:11', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTaskRequest', 'updateAtEnd', 'm2-date', '至', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-09 17:51:03', null, '2017-11-21 02:40:11', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TUpdateTaskRequest', 'taskId', null, 'taskId', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, 'id', 0, '2017-11-09 18:29:56', null, '2017-11-28 10:34:25', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TUpdateTaskRequest', 'parentTaskId', null, 'parentTaskId', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 0, '2017-11-09 18:29:56', null, '2017-11-23 19:22:14', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TUpdateTaskRequest', 'businessTypeId', 'o2-task-business-type-picker', '业务类型', 1, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-09 18:29:56', null, '2017-11-28 18:11:05', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TUpdateTaskRequest', 'taskSubject', 'o2-textarea', '标题', 1, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-09 18:29:56', null, '2017-12-05 14:26:08', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TUpdateTaskRequest', 'companyId', 'o2-company-picker', '公司', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-09 18:29:56', null, '2017-11-23 22:00:12', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TUpdateTaskRequest', 'planAt', 'o2-input-date', '计划日期', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-09 18:29:56', null, '2017-11-23 22:00:12', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TUpdateTaskRequest', 'handlerId', 'o2-staff-picker', '经办人', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-09 18:29:56', null, '2017-11-23 22:00:12', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TUpdateTaskRequest', 'problemDesc', 'o2-textarea', '工单问题', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-09 18:29:56', null, '2017-12-05 14:27:31', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TUpdateTaskRequest', 'resultDesc', 'o2-textarea', '处理结果', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-09 18:29:56', null, '2017-12-05 14:29:19', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TUpdateTaskRequest', 'questions', 'o2-question-input', '问题', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-09 18:29:57', null, '2017-11-28 11:19:37', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TUpdateTaskRequest', 'improvements', 'o2-improvement-input', '改进措施', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-09 18:29:57', null, '2017-11-28 11:19:37', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TUpdateTaskRequest', 'attachment', null, '附件', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 0, '2017-11-09 18:29:57', null, '2017-11-23 19:27:11', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TUpdateTaskRequest', 'remark', 'o2-textarea', '备注', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 0, '2017-11-09 18:29:57', null, '2017-11-23 19:27:11', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTask', 'taskSubject', null, '标题', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-09 17:06:26', null, '2017-12-05 14:26:08', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTask', 'status', null, '状态', 0, 0, null, 0, 0, null, null, null, null, null, null, null, '[{"label":"待处理","value":1},{"label":"处理中","value":2},{"label":"已处理","value":3},{"label":"无需处理","value":4}]', null, null, null, null, 1, '2017-11-09 17:07:52', null, '2017-12-07 10:32:06', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTask', 'type', null, '工单类型', 0, 0, null, 0, 0, null, null, null, null, null, null, null, '[{"label":"待办事项","value":1},{"label":"投诉","value":2},{"label":"回访记录","value":3}]', null, null, null, null, 1, '2017-11-09 17:09:24', null, '2017-12-07 10:37:57', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTask', 'companyId', null, 'companyId', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 0, '2017-11-09 17:23:20', null, '2017-11-09 17:26:24', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTask', 'businessTypeName', null, '业务类型', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-09 17:23:20', null, '2017-12-04 10:25:06', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTask', 'priority', null, '优先级', 0, 0, null, 0, 0, null, null, null, null, null, null, null, '[{"label":"高","value":1},{"label":"中","value":2},{"label":"低","value":3}]', null, null, null, null, 1, '2017-11-09 17:23:20', null, '2017-12-07 10:38:33', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TTask', 'planAt', null, '计划时间', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-09 17:23:20', null, '2017-11-09 17:23:20', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TSuggestion', 'id', null, 'id', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 0, '2017-11-10 22:05:55', null, '2017-11-10 22:14:36', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TSuggestion', 'type', null, '意见类型', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-10 22:06:24', null, '2017-11-20 23:33:26', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TSuggestion', 'content', null, '内容', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-10 22:06:24', null, '2017-11-10 22:06:24', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TSuggestion', 'labels', null, '标签', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-10 22:06:24', null, '2017-11-10 22:06:24', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TSuggestion', 'assistance', null, '帮助', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-10 22:06:24', null, '2017-11-10 22:06:24', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TSuggestion', 'createdAt', null, '创建时间', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 0, '2017-11-10 22:06:24', null, '2017-11-10 22:14:36', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TSuggestion', 'creator', null, '创建人', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 0, '2017-11-10 22:06:24', null, '2017-12-01 17:07:17', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TSuggestion', 'updatedAt', null, '更新时间', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-10 22:06:24', null, '2017-11-10 22:06:24', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TSuggestion', 'updater', null, '更新人', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-10 22:06:24', null, '2017-12-01 17:12:45', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TSuggestion', 'typeName', null, '意见类型', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 0, '2017-11-10 22:11:59', null, '2017-11-20 23:33:26', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TSuggestionRequest', 'type', 'm2-select-list', '意见类型', 0, 0, null, 1, 0, null, null, null, null, null, null, null, '[{"label":"问题","value":1},{"label":"改进","value":2}]', 'label', 'value', null, null, 1, '2017-11-10 22:21:56', null, '2017-12-07 16:35:38', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TSuggestionRequest', 'labels', 'm2-text', '标签', 0, 0, null, 1, 0, null, null, null, null, null, null, null, '', '', '', null, null, 1, '2017-11-10 22:21:56', null, '2017-11-10 23:58:37', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TSuggestionRequest', 'updatedAtStart', 'm2-date', '更新日期', 0, 0, null, 1, 0, null, null, null, null, null, null, null, '', null, null, null, null, 1, '2017-11-10 22:21:56', null, '2017-11-13 23:24:47', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TSuggestionRequest', 'updatedAtEnd', 'm2-date', '至', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-10 22:21:56', null, '2017-11-13 23:24:47', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TSaveSuggestion', 'id', null, 'id', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 0, '2017-11-10 22:40:44', null, '2017-11-10 22:41:26', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TSaveSuggestion', 'type', 'm2-select-list', '意见类型', 1, 0, null, 1, 0, null, null, null, null, null, null, null, '[{"label":"问题","value":1},{"label":"改进","value":2}]', 'label', 'value', null, null, 1, '2017-11-10 22:40:44', null, '2017-12-07 16:35:38', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TSaveSuggestion', 'content', 'm2-text-area', '内容', 1, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-10 22:40:44', null, '2017-12-05 15:37:44', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TSaveSuggestion', 'labels', 'm2-text-area', '标签', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, '标签， 多个标签逗号分隔', null, 1, '2017-11-10 22:40:44', null, '2017-11-10 23:46:34', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TSaveSuggestion', 'assistance', 'm2-text-area', '帮助', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-10 22:40:44', null, '2017-11-10 23:46:34', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TBusinessTypeRequest', 'businessTypeId', 'm2-task-business-type-picker', '业务类型', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-10 22:50:00', null, '2017-11-30 14:00:53', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TBusinessTypeRequest', 'updateAtStart', 'm2-date', '更新日期', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-10 22:50:00', null, '2017-11-13 19:32:45', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TBusinessTypeRequest', 'updateAtEnd', null, '至', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 0, '2017-11-10 22:50:00', null, '2017-11-13 19:32:45', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TSaveBusinessType', 'typeName', null, '业务类型', 1, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-10 23:01:33', null, '2017-11-13 22:28:19', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TSaveBusinessType', 'suggestionContent', 'm2-text-area', '指导意见', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-10 23:01:33', null, '2017-11-13 22:28:19', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TSaveBusinessType', 'questions', 'm2-question', '问题', 0, 1, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-10 23:01:33', null, '2017-12-01 16:12:21', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TSaveBusinessType', 'improvements', 'm2-improvement', '改进措施', 0, 1, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-10 23:01:33', null, '2017-12-01 16:15:14', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TBusinessType', 'id', null, 'id', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-10 23:01:33', null, '2017-11-10 23:01:33', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TBusinessType', 'typeName', null, '业务类型', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-10 23:01:33', null, '2017-11-10 23:01:33', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TBusinessType', 'suggestionContent', null, '指导意见', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-10 23:01:33', null, '2017-11-10 23:01:33', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TBusinessType', 'questions2Str', 'm2-question', '问题', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-10 23:01:33', null, '2017-12-01 17:14:26', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TBusinessType', 'improvements2Str', 'm2-improvement', '改进措施', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-10 23:01:33', null, '2017-12-01 17:15:17', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TBusinessType', 'createdAt', null, '创建时间', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-10 23:01:33', null, '2017-11-10 23:01:33', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TBusinessType', 'creator', null, '创建人', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-10 23:01:33', null, '2017-12-01 17:07:17', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TBusinessType', 'updatedAt', null, '更新时间 ', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-10 23:01:33', null, '2017-11-10 23:01:33', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TBusinessType', 'updater', null, '操作人', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-10 23:01:33', null, '2017-12-01 17:12:45', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TCreateTaskRequest', 'parentTaskId', null, 'parentTaskId', 0, 0, null, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null, 0, '2017-11-17 02:02:30', null, '2017-11-17 02:22:49', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TCreateTaskRequest', 'type', 'm2-select-list', '工单类型', 1, 0, null, 1, 0, null, null, null, null, null, null, null, '[{"label":"待办事项","value":1},{"label":"投诉","value":2},{"label":"回访记录","value":3}]', 'label', 'value', null, null, 1, '2017-11-17 02:02:30', null, '2017-12-07 16:35:38', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TCreateTaskRequest', 'status', 'm2-select-list', '状态', 1, 0, null, 1, 0, null, null, null, null, null, null, null, '[{"label":"待处理","value":1},{"label":"处理中","value":2},{"label":"已处理","value":3},{"label":"无需处理","value":4}]', 'label', 'value', null, null, 1, '2017-11-17 02:02:30', null, '2017-12-07 16:35:38', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TCreateTaskRequest', 'businessTypeId', 'm2-task-business-type-picker', '业务类型', 1, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-17 02:02:30', null, '2017-12-01 10:50:09', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TCreateTaskRequest', 'priority', 'm2-select-list', '优先级', 1, 0, null, 1, 0, null, null, null, null, null, null, null, '[{"label":"高","value":1},{"label":"中","value":2},{"label":"低","value":3}]', 'label', 'value', null, null, 1, '2017-11-17 02:02:30', null, '2017-12-07 16:35:38', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TCreateTaskRequest', 'taskSubject', 'm2-text-area', '标题', 1, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-17 02:02:30', null, '2017-12-05 14:26:08', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TCreateTaskRequest', 'companyId', 'm2-company-picker', '公司', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-17 02:02:30', null, '2017-11-20 22:42:34', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TCreateTaskRequest', 'communicationStyle', 'm2-select-list', '沟通方式 ', 0, 0, null, 1, 0, null, null, null, null, null, null, null, '[{"label":"微信","value":1},{"label":"QQ","value":2},{"label":"短信","value":3},{"label":"电话","value":4},{"label":"实地拜访","value":5},{"label":"其它","value":6}]', 'label', 'value', null, null, 1, '2017-11-17 02:02:30', null, '2017-12-07 16:35:38', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TCreateTaskRequest', 'planAt', 'm2-date', '计划日期', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-17 02:02:30', null, '2017-11-17 02:44:43', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TCreateTaskRequest', 'handlerId', 'm2-staff-picker', '经办人', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-17 02:02:30', null, '2017-11-20 22:42:34', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TCreateTaskRequest', 'problemDesc', 'm2-text-area', '工单问题', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-17 02:02:30', null, '2017-12-05 14:27:31', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TCreateTaskRequest', 'questions', 'm2-question-input', '问题', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-17 02:02:30', null, '2017-11-29 19:11:59', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TCreateTaskRequest', 'improvements', 'm2-improvement-input', '改进措施', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-17 02:02:30', null, '2017-12-01 16:14:56', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TCreateTaskRequest', 'attachment', 'm2-file', '附件', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-17 02:02:30', null, '2017-11-20 23:05:13', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TCreateTaskRequest', 'remark', 'm2-text-area', '备注', 0, 0, null, 1, 0, null, null, null, null, null, null, null, null, null, null, null, null, 1, '2017-11-17 02:02:30', null, '2017-11-20 22:44:13', null, null);
INSERT INTO metadb.fields (struct_name, name, element, label, required, multi, format, editable, validate, length, max_length, min_length, `regexp`, prompt, min, max, candidates, candidate_label, candidate_value, placeholder, src_key, visible, created_at, created_by, updated_at, updated_by, disabled) VALUES ('com.isuwang.soa.task.domain.TCreateTaskRequest', 'resultDesc', 'm2-text-area', '处理结果', 0, 0, null, 1, 0, null, null, null, null, null, null, null, '', 'label', 'value', null, null, 1, '2017-11-17 02:02:30', null, '2017-12-05 14:29:19', null, null);