package com.isuwang.soa.task.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class TBusinessTypeResponse{
        
            /**
            *
            **/
            public com.isuwang.soa.common.util.TPageResponse pageResponse ;
            public com.isuwang.soa.common.util.TPageResponse getPageResponse(){ return this.pageResponse; }
            public void setPageResponse(com.isuwang.soa.common.util.TPageResponse pageResponse){ this.pageResponse = pageResponse; }

            public com.isuwang.soa.common.util.TPageResponse pageResponse(){ return this.pageResponse; }
            public TBusinessTypeResponse pageResponse(com.isuwang.soa.common.util.TPageResponse pageResponse){ this.pageResponse = pageResponse; return this; }
          
            /**
            *
            **/
            public java.util.List<com.isuwang.soa.task.domain.TBusinessType> rows = new java.util.ArrayList();
            public java.util.List<com.isuwang.soa.task.domain.TBusinessType> getRows(){ return this.rows; }
            public void setRows(java.util.List<com.isuwang.soa.task.domain.TBusinessType> rows){ this.rows = rows; }

            public java.util.List<com.isuwang.soa.task.domain.TBusinessType> rows(){ return this.rows; }
            public TBusinessTypeResponse rows(java.util.List<com.isuwang.soa.task.domain.TBusinessType> rows){ this.rows = rows; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("pageResponse").append("\":").append(this.pageResponse.toString()).append(",");
    stringBuilder.append("\"").append("rows").append("\":").append(this.rows).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      