package com.isuwang.soa.task.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class TCreateTaskAttachment{
        
            /**
            *

 任务id

            **/
            public int taskId ;
            public int getTaskId(){ return this.taskId; }
            public void setTaskId(int taskId){ this.taskId = taskId; }

            public int taskId(){ return this.taskId; }
            public TCreateTaskAttachment taskId(int taskId){ this.taskId = taskId; return this; }
          
            /**
            *

 附件id(阿里云文件id)

            **/
            public String attachmentId ;
            public String getAttachmentId(){ return this.attachmentId; }
            public void setAttachmentId(String attachmentId){ this.attachmentId = attachmentId; }

            public String attachmentId(){ return this.attachmentId; }
            public TCreateTaskAttachment attachmentId(String attachmentId){ this.attachmentId = attachmentId; return this; }
          
            /**
            *

 附件文件名

            **/
            public String attachmentName ;
            public String getAttachmentName(){ return this.attachmentName; }
            public void setAttachmentName(String attachmentName){ this.attachmentName = attachmentName; }

            public String attachmentName(){ return this.attachmentName; }
            public TCreateTaskAttachment attachmentName(String attachmentName){ this.attachmentName = attachmentName; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("taskId").append("\":").append(this.taskId).append(",");
    stringBuilder.append("\"").append("attachmentId").append("\":\"").append(this.attachmentId).append("\",");
    stringBuilder.append("\"").append("attachmentName").append("\":\"").append(this.attachmentName).append("\",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      