package com.isuwang.soa.task.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class TSuggestionRequest{
        
            /**
            *
            **/
            public com.isuwang.soa.common.util.TPageRequest pageRequest ;
            public com.isuwang.soa.common.util.TPageRequest getPageRequest(){ return this.pageRequest; }
            public void setPageRequest(com.isuwang.soa.common.util.TPageRequest pageRequest){ this.pageRequest = pageRequest; }

            public com.isuwang.soa.common.util.TPageRequest pageRequest(){ return this.pageRequest; }
            public TSuggestionRequest pageRequest(com.isuwang.soa.common.util.TPageRequest pageRequest){ this.pageRequest = pageRequest; return this; }
          
            /**
            *

 意见类型，1: 问题, 2: 改进

            **/
            public Optional<Integer> type = Optional.empty();
            public Optional<Integer> getType(){ return this.type; }
            public void setType(Optional<Integer> type){ this.type = type; }

            public Optional<Integer> type(){ return this.type; }
            public TSuggestionRequest type(Optional<Integer> type){ this.type = type; return this; }
          
            /**
            *

 标签，多个标签逗号分隔

            **/
            public Optional<String> labels = Optional.empty();
            public Optional<String> getLabels(){ return this.labels; }
            public void setLabels(Optional<String> labels){ this.labels = labels; }

            public Optional<String> labels(){ return this.labels; }
            public TSuggestionRequest labels(Optional<String> labels){ this.labels = labels; return this; }
          
            /**
            *

 更新日期（起始）

            **/
            public Optional<Long> updateAtStart = Optional.empty();
            public Optional<Long> getUpdateAtStart(){ return this.updateAtStart; }
            public void setUpdateAtStart(Optional<Long> updateAtStart){ this.updateAtStart = updateAtStart; }

            public Optional<Long> updateAtStart(){ return this.updateAtStart; }
            public TSuggestionRequest updateAtStart(Optional<Long> updateAtStart){ this.updateAtStart = updateAtStart; return this; }
          
            /**
            *

 更新日期（结束）

            **/
            public Optional<Long> updateAtEnd = Optional.empty();
            public Optional<Long> getUpdateAtEnd(){ return this.updateAtEnd; }
            public void setUpdateAtEnd(Optional<Long> updateAtEnd){ this.updateAtEnd = updateAtEnd; }

            public Optional<Long> updateAtEnd(){ return this.updateAtEnd; }
            public TSuggestionRequest updateAtEnd(Optional<Long> updateAtEnd){ this.updateAtEnd = updateAtEnd; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("pageRequest").append("\":").append(this.pageRequest.toString()).append(",");
    stringBuilder.append("\"").append("type").append("\":").append(this.type.isPresent()?this.type.get():null).append(",");
    stringBuilder.append("\"").append("labels").append("\":\"").append(this.labels.isPresent()?this.labels.get():null).append("\",");
    stringBuilder.append("\"").append("updateAtStart").append("\":").append(this.updateAtStart.isPresent()?this.updateAtStart.get():null).append(",");
    stringBuilder.append("\"").append("updateAtEnd").append("\":").append(this.updateAtEnd.isPresent()?this.updateAtEnd.get():null).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      