package com.isuwang.soa.task.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class TTaskAttachment{
        
            /**
            *
            **/
            public int id ;
            public int getId(){ return this.id; }
            public void setId(int id){ this.id = id; }

            public int id(){ return this.id; }
            public TTaskAttachment id(int id){ this.id = id; return this; }
          
            /**
            *

 任务id

            **/
            public int taskId ;
            public int getTaskId(){ return this.taskId; }
            public void setTaskId(int taskId){ this.taskId = taskId; }

            public int taskId(){ return this.taskId; }
            public TTaskAttachment taskId(int taskId){ this.taskId = taskId; return this; }
          
            /**
            *

 附件id(阿里云文件id)

            **/
            public String attachmentId ;
            public String getAttachmentId(){ return this.attachmentId; }
            public void setAttachmentId(String attachmentId){ this.attachmentId = attachmentId; }

            public String attachmentId(){ return this.attachmentId; }
            public TTaskAttachment attachmentId(String attachmentId){ this.attachmentId = attachmentId; return this; }
          
            /**
            *

 附件文件名

            **/
            public String attachmentName ;
            public String getAttachmentName(){ return this.attachmentName; }
            public void setAttachmentName(String attachmentName){ this.attachmentName = attachmentName; }

            public String attachmentName(){ return this.attachmentName; }
            public TTaskAttachment attachmentName(String attachmentName){ this.attachmentName = attachmentName; return this; }
          
            /**
            *



            **/
            public long createdAt ;
            public long getCreatedAt(){ return this.createdAt; }
            public void setCreatedAt(long createdAt){ this.createdAt = createdAt; }

            public long createdAt(){ return this.createdAt; }
            public TTaskAttachment createdAt(long createdAt){ this.createdAt = createdAt; return this; }
          
            /**
            *



            **/
            public Optional<Integer> createdBy = Optional.empty();
            public Optional<Integer> getCreatedBy(){ return this.createdBy; }
            public void setCreatedBy(Optional<Integer> createdBy){ this.createdBy = createdBy; }

            public Optional<Integer> createdBy(){ return this.createdBy; }
            public TTaskAttachment createdBy(Optional<Integer> createdBy){ this.createdBy = createdBy; return this; }
          
            /**
            *



            **/
            public long updatedAt ;
            public long getUpdatedAt(){ return this.updatedAt; }
            public void setUpdatedAt(long updatedAt){ this.updatedAt = updatedAt; }

            public long updatedAt(){ return this.updatedAt; }
            public TTaskAttachment updatedAt(long updatedAt){ this.updatedAt = updatedAt; return this; }
          
            /**
            *



            **/
            public Optional<Integer> updatedBy = Optional.empty();
            public Optional<Integer> getUpdatedBy(){ return this.updatedBy; }
            public void setUpdatedBy(Optional<Integer> updatedBy){ this.updatedBy = updatedBy; }

            public Optional<Integer> updatedBy(){ return this.updatedBy; }
            public TTaskAttachment updatedBy(Optional<Integer> updatedBy){ this.updatedBy = updatedBy; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("id").append("\":").append(this.id).append(",");
    stringBuilder.append("\"").append("taskId").append("\":").append(this.taskId).append(",");
    stringBuilder.append("\"").append("attachmentId").append("\":\"").append(this.attachmentId).append("\",");
    stringBuilder.append("\"").append("attachmentName").append("\":\"").append(this.attachmentName).append("\",");
    stringBuilder.append("\"").append("createdAt").append("\":").append(this.createdAt).append(",");
    stringBuilder.append("\"").append("createdBy").append("\":").append(this.createdBy.isPresent()?this.createdBy.get():null).append(",");
    stringBuilder.append("\"").append("updatedAt").append("\":").append(this.updatedAt).append(",");
    stringBuilder.append("\"").append("updatedBy").append("\":").append(this.updatedBy.isPresent()?this.updatedBy.get():null).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      