package com.isuwang.soa.task.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class TTaskLog{
        
            /**
            *
            **/
            public int id ;
            public int getId(){ return this.id; }
            public void setId(int id){ this.id = id; }

            public int id(){ return this.id; }
            public TTaskLog id(int id){ this.id = id; return this; }
          
            /**
            *

 任务id

            **/
            public int taskId ;
            public int getTaskId(){ return this.taskId; }
            public void setTaskId(int taskId){ this.taskId = taskId; }

            public int taskId(){ return this.taskId; }
            public TTaskLog taskId(int taskId){ this.taskId = taskId; return this; }
          
            /**
            *

 操作名

            **/
            public String operation ;
            public String getOperation(){ return this.operation; }
            public void setOperation(String operation){ this.operation = operation; }

            public String operation(){ return this.operation; }
            public TTaskLog operation(String operation){ this.operation = operation; return this; }
          
            /**
            *

 操作字段名

            **/
            public Optional<String> operField = Optional.empty();
            public Optional<String> getOperField(){ return this.operField; }
            public void setOperField(Optional<String> operField){ this.operField = operField; }

            public Optional<String> operField(){ return this.operField; }
            public TTaskLog operField(Optional<String> operField){ this.operField = operField; return this; }
          
            /**
            *

 原值

            **/
            public Optional<String> oldValue = Optional.empty();
            public Optional<String> getOldValue(){ return this.oldValue; }
            public void setOldValue(Optional<String> oldValue){ this.oldValue = oldValue; }

            public Optional<String> oldValue(){ return this.oldValue; }
            public TTaskLog oldValue(Optional<String> oldValue){ this.oldValue = oldValue; return this; }
          
            /**
            *

 新值

            **/
            public Optional<String> newValue = Optional.empty();
            public Optional<String> getNewValue(){ return this.newValue; }
            public void setNewValue(Optional<String> newValue){ this.newValue = newValue; }

            public Optional<String> newValue(){ return this.newValue; }
            public TTaskLog newValue(Optional<String> newValue){ this.newValue = newValue; return this; }
          
            /**
            *



            **/
            public long createdAt ;
            public long getCreatedAt(){ return this.createdAt; }
            public void setCreatedAt(long createdAt){ this.createdAt = createdAt; }

            public long createdAt(){ return this.createdAt; }
            public TTaskLog createdAt(long createdAt){ this.createdAt = createdAt; return this; }
          
            /**
            *



            **/
            public Optional<Integer> createdBy = Optional.empty();
            public Optional<Integer> getCreatedBy(){ return this.createdBy; }
            public void setCreatedBy(Optional<Integer> createdBy){ this.createdBy = createdBy; }

            public Optional<Integer> createdBy(){ return this.createdBy; }
            public TTaskLog createdBy(Optional<Integer> createdBy){ this.createdBy = createdBy; return this; }
          
            /**
            *



            **/
            public long updatedAt ;
            public long getUpdatedAt(){ return this.updatedAt; }
            public void setUpdatedAt(long updatedAt){ this.updatedAt = updatedAt; }

            public long updatedAt(){ return this.updatedAt; }
            public TTaskLog updatedAt(long updatedAt){ this.updatedAt = updatedAt; return this; }
          
            /**
            *



            **/
            public Optional<Integer> updatedBy = Optional.empty();
            public Optional<Integer> getUpdatedBy(){ return this.updatedBy; }
            public void setUpdatedBy(Optional<Integer> updatedBy){ this.updatedBy = updatedBy; }

            public Optional<Integer> updatedBy(){ return this.updatedBy; }
            public TTaskLog updatedBy(Optional<Integer> updatedBy){ this.updatedBy = updatedBy; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("id").append("\":").append(this.id).append(",");
    stringBuilder.append("\"").append("taskId").append("\":").append(this.taskId).append(",");
    stringBuilder.append("\"").append("operation").append("\":\"").append(this.operation).append("\",");
    stringBuilder.append("\"").append("operField").append("\":\"").append(this.operField.isPresent()?this.operField.get():null).append("\",");
    stringBuilder.append("\"").append("oldValue").append("\":\"").append(this.oldValue.isPresent()?this.oldValue.get():null).append("\",");
    stringBuilder.append("\"").append("newValue").append("\":\"").append(this.newValue.isPresent()?this.newValue.get():null).append("\",");
    stringBuilder.append("\"").append("createdAt").append("\":").append(this.createdAt).append(",");
    stringBuilder.append("\"").append("createdBy").append("\":").append(this.createdBy.isPresent()?this.createdBy.get():null).append(",");
    stringBuilder.append("\"").append("updatedAt").append("\":").append(this.updatedAt).append(",");
    stringBuilder.append("\"").append("updatedBy").append("\":").append(this.updatedBy.isPresent()?this.updatedBy.get():null).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      