package com.isuwang.soa.scala.task.domain

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        case class TCreateTaskAttachment(

         /**
        *

 任务id

        **/
        
        taskId : Int, /**
        *

 附件id(阿里云文件id)

        **/
        
        attachmentId : String, /**
        *

 附件文件名

        **/
        
        attachmentName : String
        )
      