package com.isuwang.soa.scala.task.domain

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        case class TSaveTaskRemark(

         /**
        *
        **/
        
        taskId : Int, /**
        *

 备注内容

        **/
        
        content : String, /**
        *
        **/
        
        id : Option[Int] = None
        )
      