package com.isuwang.soa.scala.task.domain

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        case class TSuggestionRequest(

         /**
        *
        **/
        
        pageRequest : com.isuwang.soa.scala.common.util.TPageRequest, /**
        *

 意见类型，1: 问题, 2: 改进

        **/
        
        `type` : Option[Int] = None, /**
        *

 标签，多个标签逗号分隔

        **/
        
        labels : Option[String] = None, /**
        *

 更新日期（起始）

        **/
        
        updateAtStart : Option[Long] = None, /**
        *

 更新日期（结束）

        **/
        
        updateAtEnd : Option[Long] = None
        )
      