package com.isuwang.soa.scala.task.domain

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        case class TTaskResponse(

         /**
        *
        **/
        
        pageResponse : com.isuwang.soa.scala.common.util.TPageResponse, /**
        *
        **/
        
        rows : List[com.isuwang.soa.scala.task.domain.TTask], /**
        *

 今日待办事项统计

        **/
        
        todayTodo : com.isuwang.soa.scala.task.domain.TSumupTaskResult, /**
        *

 超时待办事项统计

        **/
        
        expiredTodo : com.isuwang.soa.scala.task.domain.TSumupTaskResult, /**
        *

 未处理投诉

        **/
        
        unhandleComplaint : com.isuwang.soa.scala.task.domain.TSumupTaskResult, /**
        *

 处理中投诉

        **/
        
        handlingComplaint : com.isuwang.soa.scala.task.domain.TSumupTaskResult, /**
        *

 当前查询条件下的统计结果

        **/
        
        sumupTotal : List[com.isuwang.soa.scala.task.domain.TSumupTotal]
        )
      