
        package com.isuwang.soa.scala.task.service

        import com.isuwang.dapeng.core.{Processor, Service}
        import com.isuwang.dapeng.core.SoaGlobalTransactional

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 
        **/
        @Service(name ="com.isuwang.soa.task.service.TaskAdminService" , version = "1.0.0")
        @Processor(className = "com.isuwang.soa.scala.task.TaskAdminServiceCodec$Processor")
        trait TaskAdminService {
        
            /**
            * 
            **/
            
            def findTasks(
            request: com.isuwang.soa.scala.task.domain.TTaskRequest ): com.isuwang.soa.scala.task.domain.TTaskResponse

          
            /**
            * 
            **/
            
            def findTaskDetailById(
            id: Int ): com.isuwang.soa.scala.task.domain.TTaskDetail

          
            /**
            * 
            **/
            
            def createTask(
            request: com.isuwang.soa.scala.task.domain.TCreateTaskRequest ): Unit

          
            /**
            * 
            **/
            
            def updateTask(
            request: com.isuwang.soa.scala.task.domain.TUpdateTaskRequest ): Unit

          
            /**
            * 
            **/
            
            def unbindSubTask(
            subTaskId: Int ): Unit

          
            /**
            * 
            **/
            
            def createTaskRemark(
            request: com.isuwang.soa.scala.task.domain.TSaveTaskRemark ): Unit

          
            /**
            * 
            **/
            
            def updateTaskRemark(
            request: com.isuwang.soa.scala.task.domain.TSaveTaskRemark ): Unit

          
            /**
            * 
            **/
            
            def deleteTaskRemark(
            id: Int ): Unit

          
            /**
            * 
            **/
            
            def createTaskLog(
            request: com.isuwang.soa.scala.task.domain.TCreateTaskLog ): Unit

          
            /**
            * 
            **/
            
            def createTaskAttachment(
            request: com.isuwang.soa.scala.task.domain.TCreateTaskAttachment ): Int

          
            /**
            * 
            **/
            
            def deleteTaskAttachment(
            id: Int ): Unit

          
            /**
            * 
            **/
            
            def findAllTaskNos4Picker(
            ): List[com.isuwang.soa.scala.task.domain.TTaskPickerContainer]

          
        }
        