
        package com.isuwang.soa.scala.task.service

        import com.isuwang.dapeng.core.{Processor, Service}
        import com.isuwang.dapeng.core.SoaGlobalTransactional

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 
        **/
        @Service(name ="com.isuwang.soa.task.service.TaskBusinessTypeService" , version = "1.0.0")
        @Processor(className = "com.isuwang.soa.scala.task.TaskBusinessTypeServiceCodec$Processor")
        trait TaskBusinessTypeService {
        
            /**
            * 
            **/
            
            def findBusinessTypes(
            request: com.isuwang.soa.scala.task.domain.TBusinessTypeRequest ): com.isuwang.soa.scala.task.domain.TBusinessTypeResponse

          
            /**
            * 
            **/
            
            def createBusinessType(
            request: com.isuwang.soa.scala.task.domain.TSaveBusinessType ): Unit

          
            /**
            * 
            **/
            
            def updateBusinessType(
            request: com.isuwang.soa.scala.task.domain.TSaveBusinessType ): Unit

          
            /**
            * 
            **/
            
            def deleteBusinessType(
            id: Int ): Unit

          
            /**
            * 
            **/
            
            def findAllBusinessTypes4Picker(
            ): List[com.isuwang.soa.scala.task.domain.TTaskPickerContainer]

          
        }
        