
        package com.isuwang.soa.scala.task.service

        import com.isuwang.dapeng.core.{Processor, Service}
        import com.isuwang.dapeng.core.SoaGlobalTransactional

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 
        **/
        @Service(name ="com.isuwang.soa.task.service.TaskSuggestionService" , version = "1.0.0")
        @Processor(className = "com.isuwang.soa.scala.task.TaskSuggestionServiceCodec$Processor")
        trait TaskSuggestionService {
        
            /**
            * 
            **/
            
            def findSuggestions(
            request: com.isuwang.soa.scala.task.domain.TSuggestionRequest ): com.isuwang.soa.scala.task.domain.TSuggestionResponse

          
            /**
            * 
            **/
            
            def createSuggestion(
            request: com.isuwang.soa.scala.task.domain.TSaveSuggestion ): Unit

          
            /**
            * 
            **/
            
            def updateSuggestion(
            request: com.isuwang.soa.scala.task.domain.TSaveSuggestion ): Unit

          
            /**
            * 
            **/
            
            def deleteSuggestion(
            id: Int ): Unit

          
            /**
            * 
            **/
            
            def findAllSuggestions4PickerByType(
            `type`: Int ): List[com.isuwang.soa.scala.task.domain.TSuggestion4Picker]

          
        }
        