package com.isuwang.soa.task.enums;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 
        **/
        public enum TaskPriority implements com.isuwang.org.apache.thrift.TEnum{
        
            /**
            *

 高

            **/
            HIGH(1),
          
            /**
            *

 中

            **/
            MEDIUM(2),
          
            /**
            *

 低

            **/
            LOW(3);
          

        private final int value;

        private TaskPriority(int value){
            this.value = value;
        }

        public int getValue(){
            return this.value;
        }

        public static TaskPriority findByValue(int value){
            switch(value){
            
                 case 1:
                    return HIGH;
               
                 case 2:
                    return MEDIUM;
               
                 case 3:
                    return LOW;
               
               default:
                   return null;
            }
        }
        }
      