package com.isuwang.soa.scala.common.util

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        case class TPageResponse(

         /**
        *

 查询的开始序号（序号从零开始）

        **/
        
        start : Int, /**
        *

 最大返回的记录数

        **/
        
        limit : Int, /**
        *

 结果记录数

        **/
        
        results : Int
        )
      