package com.isuwang.soa.scala.task.enums;

      class TaskPriority private(val id: Int, val name: String) extends com.isuwang.dapeng.core.enums.TEnum(id,name) {}

      /**
       * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

      * 
      **/
      object TaskPriority {

      
            val HIGH = new TaskPriority(1, "高")
          
            val MEDIUM = new TaskPriority(2, "中")
          
            val LOW = new TaskPriority(3, "低")
          
      val UNDEFINED = new TaskPriority(-1,"UNDEFINED") // undefined enum
      

      def findByValue(v: Int): TaskPriority = {
        v match {
          case 1 => HIGH
            case 2 => MEDIUM
            case 3 => LOW
            
          case _ => new TaskPriority(v,"#"+ v)
        }
      }

      def apply(v: Int) = findByValue(v)
      def unapply(v: TaskPriority): Option[Int] = Some(v.id)

    }
    