package com.isuwang.soa.common.util;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *

 请求头

        **/
        public class RequestHeader{
        
            /**
            *

 操作人ID

            **/
            public int operatorId ;
            public int getOperatorId(){ return this.operatorId; }
            public void setOperatorId(int operatorId){ this.operatorId = operatorId; }

            public int operatorId(){ return this.operatorId; }
            public RequestHeader operatorId(int operatorId){ this.operatorId = operatorId; return this; }
          
            /**
            *

  操作人名称

            **/
            public String operatorName ;
            public String getOperatorName(){ return this.operatorName; }
            public void setOperatorName(String operatorName){ this.operatorName = operatorName; }

            public String operatorName(){ return this.operatorName; }
            public RequestHeader operatorName(String operatorName){ this.operatorName = operatorName; return this; }
          
            /**
            *

 客户编号

            **/
            public Optional<Integer> customerId = Optional.empty();
            public Optional<Integer> getCustomerId(){ return this.customerId; }
            public void setCustomerId(Optional<Integer> customerId){ this.customerId = customerId; }

            public Optional<Integer> customerId(){ return this.customerId; }
            public RequestHeader customerId(Optional<Integer> customerId){ this.customerId = customerId; return this; }
          
            /**
            *

 客户名称

            **/
            public Optional<String> customerName = Optional.empty();
            public Optional<String> getCustomerName(){ return this.customerName; }
            public void setCustomerName(Optional<String> customerName){ this.customerName = customerName; }

            public Optional<String> customerName(){ return this.customerName; }
            public RequestHeader customerName(Optional<String> customerName){ this.customerName = customerName; return this; }
          
            /**
            *

 调用源

            **/
            public Optional<com.isuwang.soa.common.util.CallerFrom> callerFrom = Optional.empty();
            public Optional<com.isuwang.soa.common.util.CallerFrom> getCallerFrom(){ return this.callerFrom; }
            public void setCallerFrom(Optional<com.isuwang.soa.common.util.CallerFrom> callerFrom){ this.callerFrom = callerFrom; }

            public Optional<com.isuwang.soa.common.util.CallerFrom> callerFrom(){ return this.callerFrom; }
            public RequestHeader callerFrom(Optional<com.isuwang.soa.common.util.CallerFrom> callerFrom){ this.callerFrom = callerFrom; return this; }
          
            /**
            *

 调用源IP

            **/
            public Optional<String> callerIP = Optional.empty();
            public Optional<String> getCallerIP(){ return this.callerIP; }
            public void setCallerIP(Optional<String> callerIP){ this.callerIP = callerIP; }

            public Optional<String> callerIP(){ return this.callerIP; }
            public RequestHeader callerIP(Optional<String> callerIP){ this.callerIP = callerIP; return this; }
          
            /**
            *

 会话编号

            **/
            public Optional<String> sessionId = Optional.empty();
            public Optional<String> getSessionId(){ return this.sessionId; }
            public void setSessionId(Optional<String> sessionId){ this.sessionId = sessionId; }

            public Optional<String> sessionId(){ return this.sessionId; }
            public RequestHeader sessionId(Optional<String> sessionId){ this.sessionId = sessionId; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("operatorId").append("\":").append(this.operatorId).append(",");
    stringBuilder.append("\"").append("operatorName").append("\":\"").append(this.operatorName).append("\",");
    stringBuilder.append("\"").append("customerId").append("\":").append(this.customerId.isPresent()?this.customerId.get():null).append(",");
    stringBuilder.append("\"").append("customerName").append("\":\"").append(this.customerName.isPresent()?this.customerName.get():null).append("\",");
    stringBuilder.append("\"").append("callerFrom").append("\":").append(this.callerFrom.isPresent()?this.callerFrom.get():null).append(",");
    stringBuilder.append("\"").append("callerIP").append("\":\"").append(this.callerIP.isPresent()?this.callerIP.get():null).append("\",");
    stringBuilder.append("\"").append("sessionId").append("\":\"").append(this.sessionId.isPresent()?this.sessionId.get():null).append("\",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      